"""Module that provides few converter functions"""

import curses
from enum import Enum, auto


class Color(Enum):
    """Colors read from user config"""
    DAY_NAMES = auto()
    WEEKENDS = auto()
    HINTS = auto()
    TODAY = auto()
    DAYS = auto()
    WEEKEND_NAMES = auto()
    BIRTHDAYS = auto()
    PROMPTS = auto()
    CONFIRMATIONS = auto()
    TITLE = auto()
    TODO = auto()
    DONE = auto()
    IMPORTANT = auto()
    TIMER = auto()
    TIMER_PAUSED = auto()
    HOLIDAYS = auto()
    EVENTS = auto()
    TIME = auto()
    WEATHER = auto()
    UNIMPORTANT = auto()
    CALENDAR_HEADER = auto()
    ACTIVE_PANE = auto()
    SEPARATOR = auto()
    EMPTY = auto()
    CALENDAR_BORDER = auto()
    DEADLINES = auto()


def initialize_colors(global_config):
    """Define all the color pairs"""
    curses.start_color()
    curses.use_default_colors()
    curses.init_pair(Color.DAY_NAMES.value, global_config.COLOR_DAY_NAMES, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.WEEKENDS.value, global_config.COLOR_WEEKENDS, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.HINTS.value, global_config.COLOR_HINTS, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.TODAY.value, global_config.COLOR_TODAY, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.DAYS.value, global_config.COLOR_DAYS, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.WEEKEND_NAMES.value, global_config.COLOR_WEEKEND_NAMES, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.BIRTHDAYS.value, global_config.COLOR_BIRTHDAYS, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.PROMPTS.value, global_config.COLOR_PROMPTS, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.CONFIRMATIONS.value, global_config.COLOR_CONFIRMATIONS, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.TITLE.value, global_config.COLOR_TITLE, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.TODO.value, global_config.COLOR_TODO, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.DONE.value, global_config.COLOR_DONE, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.IMPORTANT.value, global_config.COLOR_IMPORTANT, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.TIMER.value, global_config.COLOR_TIMER, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.TIMER_PAUSED.value, global_config.COLOR_TIMER_PAUSED, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.HOLIDAYS.value, global_config.COLOR_HOLIDAYS, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.EVENTS.value, global_config.COLOR_EVENTS, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.TIME.value, global_config.COLOR_TIME, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.WEATHER.value, global_config.COLOR_WEATHER, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.UNIMPORTANT.value, global_config.COLOR_UNIMPORTANT, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.CALENDAR_HEADER.value, global_config.COLOR_CALENDAR_HEADER, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.ACTIVE_PANE.value, global_config.COLOR_ACTIVE_PANE, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.SEPARATOR.value, global_config.COLOR_SEPARATOR, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.EMPTY.value, global_config.COLOR_BACKGROUND, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.CALENDAR_BORDER.value, global_config.COLOR_CALENDAR_BORDER, global_config.COLOR_BACKGROUND)
    curses.init_pair(Color.DEADLINES.value, global_config.COLOR_DEADLINES, global_config.COLOR_BACKGROUND)
